account/urls.py
from django.conf.urls import url
from django.views.static import serve
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from account.views import *

app_name = 'account'

urlpatterns = [
    path('account/', account, name="create_account" ),

]

main/urls.py
from django.urls import path, re_path
from main.views import (Dashboard, CourierAccountLogin,
 CourierAccountRegister, Homepage)
from . import views
from main.views import *

app_name = 'main'

urlpatterns = []

templates/extend_registration/create_account.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Register Page</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

</head>
<body>

	{% load crispy_forms_tags %}  

<div class="container  d-flex justify-content-center">
	<div class="col-lg-4 mt-4  bg-white shadow shadow-lg p-4">
			{% for message in messages %}
				<div class="alert alert-danger">
					{{message}}
				</div>
			{% endfor %}
			<div class="bg-white shadow shadow-sm rounded mb-4 text text-center text-dark p-2">
				<h1>Register</h1>
			</div>
			<form method="POST" accept="{% url 'account:create_account' %}">
				{% csrf_token %}
				{{ forms|crispy }}                    
				<button class="btn btn-primary btn-block"  type="submit">Register</button>
			</form>
			<p class="text-center">If you already have an account, <a href="/sub-admin">login</a> instead.</p>
	</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>